//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFAC.WindowsForms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GFAC.WindowsForms.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string btnSelectFile {
            get {
                return ResourceManager.GetString("btnSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Profile.
        /// </summary>
        internal static string btnSelectProfile {
            get {
                return ResourceManager.GetString("btnSelectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Profile.
        /// </summary>
        internal static string lblCalculationProfile {
            get {
                return ResourceManager.GetString("lblCalculationProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        internal static string lblColumnName {
            get {
                return ResourceManager.GetString("lblColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string lblColumns {
            get {
                return ResourceManager.GetString("lblColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string lblColumnScore {
            get {
                return ResourceManager.GetString("lblColumnScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lblColumnType {
            get {
                return ResourceManager.GetString("lblColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Responses.
        /// </summary>
        internal static string lblCorrectResponses {
            get {
                return ResourceManager.GetString("lblCorrectResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Type.
        /// </summary>
        internal static string lblDefaultColumnType {
            get {
                return ResourceManager.GetString("lblDefaultColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputfile.
        /// </summary>
        internal static string lblInputFile {
            get {
                return ResourceManager.GetString("lblInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Name.
        /// </summary>
        internal static string lblProfileName {
            get {
                return ResourceManager.GetString("lblProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session name.
        /// </summary>
        internal static string lblSessionName {
            get {
                return ResourceManager.GetString("lblSessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        internal static string tabFinalScore {
            get {
                return ResourceManager.GetString("tabFinalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responses.
        /// </summary>
        internal static string tabResponses {
            get {
                return ResourceManager.GetString("tabResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string tabSource {
            get {
                return ResourceManager.GetString("tabSource", resourceCulture);
            }
        }
    }
}
